### ISSUE TITLE
An SSL Error has occurred and a secure connection to the server cannot be made.

### ISSUE THREAD

**Issue by zuoez02** [mudkipme/MoeMemos#1]
My memos server is deployed at home and can be access through https://url:50518, which port is not 443. I use self-signed certificate.

When I use this path and try to login, I get the error message "An SSL Error has occurred and a secure connection to the server cannot be made.".

**Comment by mudkipme** [comment]
When using a self-signed certificate, please manually trust the certificate on your devices:

You can send the certificate via email, open it, and then follow these steps:
https://support.apple.com/en-us/HT204477

**Comment by ShakeChanDev** [comment]
我也遇到同样的问题了，最后是直接用群晖做了个反代就解决了
