### ISSUE TITLE
没有解释markdown内容

### ISSUE THREAD

**Issue by chinobing** [mudkipme/MoeMemos#10]
反馈一下：好像只是单纯显示文本没有转换为markdown，谢谢。

**Comment by mudkipme** [comment]
Currently the app uses SwiftUI's native Markdown parser and only supports inline formats and images. It's planned to support more markdown formats with https://github.com/apple/swift-markdown in future, but it will take longer time.

**Comment by chinobing** [comment]
Thanks for your hard work on MoeMemos. I am looking forward to enhancements on it.
