### ISSUE TITLE
"Unable to read data because its format is incorrect"

### ISSUE THREAD

**Issue by wangningyu** [mudkipme/MoeMemos#100]
I installed MemOS(0.14.1) in the docker environment, and the browser(https) opened normally. When I opened the IOS APP (the latest version), I was prompted with "Unable to read data because its format is incorrect"

Thank you.

![MoeMemos](https://github.com/mudkipme/MoeMemos/assets/8290780/af8ae2b8-2eb0-4e64-98ee-646e969ccc2e)

**Comment by mudkipme** [comment]
Moe Memos 1.5.4 fixed compatibility with Memos 0.14.1 and is waiting for App Store review.

In the meantime, you can upgrade with TestFlight: https://testflight.apple.com/join/YVHheZ50

**Comment by wangningyu** [comment]
thanks!

**Comment by mudkipme** [comment]
Moe Memos 1.5.4 is approved.
