### ISSUE TITLE
The data couldn't be read because it is…

### ISSUE THREAD

**Issue by hanimedialab** [mudkipme/MoeMemos#101]
When I try to sign in, I get an error message.
"The data couldn't be read because it is…"
I've set up https on my server, and I'm logged in fine on the web. 
![photo_2023-07-24 14 17 58](https://github.com/mudkipme/MoeMemos/assets/134350874/2a66e641-fc39-4483-af7b-c6761bb2e39c)
![photo_2023-07-24 14 17 55](https://github.com/mudkipme/MoeMemos/assets/134350874/fe569193-4513-45e8-af66-8207126a0a8a)

Is anyone else having the same problem?

iPhone XS, iOS 17.0

**Comment by mudkipme** [comment]
Moe Memos 1.5.4 fixed compatibility with Memos 0.14.1 and is waiting for App Store review.

In the meantime, you can upgrade with TestFlight: https://testflight.apple.com/join/YVHheZ50

**Comment by hanimedialab** [comment]
Thanks a lot!

**Comment by mudkipme** [comment]
Moe Memos 1.5.4 is approved.

**Comment by derbirch** [comment]
I wonder are there any changes in API for the newly released Memos that could cause connectivity issues? The latest version won’t work again, I also tried the TestFlight version and it didn’t work either

**Comment by mudkipme** [comment]
Moe Memos isn’t compatible with Memos 0.15 yet. I’ll work on a fix soon.

**Comment by derbirch** [comment]
> Moe Memos isn’t compatible with Memos 0.15 yet. I’ll work on a fix soon.

Thanks, I will use the web version for now

**Comment by kernelkaribou** [comment]
Is this still a problem? I see that the version on the App Store indicates it is compatible with 0.15 but I am running v0.17.0 not sure if new changes causing more compatibility issues. I am getting the same error above with these versions.

Thanks for the app!
