### ISSUE TITLE
language support

### ISSUE THREAD

**Issue by Ghost108** [mudkipme/MoeMemos#105]
Hi!

thanks for this app!
Can you support different languages?
for me I would like to use the german language.

**Comment by mudkipme** [comment]
Moe Memos is aimed to support as many languages as possible :)

If you know German-language you are welcome to submit a pull request (like #41) to help add localization to this app 😄

**Comment by Ghost108** [comment]
Here we go:
I used this file as template:

https://github.com/mudkipme/MoeMemos/blob/main/MoeMemos/Resources/Localization/en.lproj/Localizable.strings


This is the translated version for german language.
can you include it please?

[(german)Localizable.strings.zip](https://github.com/mudkipme/MoeMemos/files/12283721/german.Localizable.strings.zip)

**Comment by mudkipme** [comment]
> 



> Here we go: I used this file as template:
> 
> https://github.com/mudkipme/MoeMemos/blob/main/MoeMemos/Resources/Localization/en.lproj/Localizable.strings
> 
> This is the translated version for german language. can you include it please?
> 
> [(german)Localizable.strings.zip](https://github.com/mudkipme/MoeMemos/files/12283721/german.Localizable.strings.zip)

Thanks! This patch is merged and will be included in next version.
