### ISSUE TITLE
The iOS MoeMemos froze when writing and editing memos

### ISSUE THREAD

**Issue by Lukas-Jang** [mudkipme/MoeMemos#107]
Since I've update the Memos version to 0.14.2, I can't write memos on my iPhone with the Memos app. It just froze when I type one or two words. And if I want to edit some previous memos, the app just crash.

**Comment by mudkipme** [comment]
Thanks for reporting. I'm looking into this issue. It seems it's a compatibility issue with iOS 15.

**Comment by Lukas-Jang** [comment]
maybe it is a problem with ios 15, i tried to run moememos on my ipad with ipados 16, it doesn't seem any crash or froze there.
