### ISSUE TITLE
没有tags和附件上传图标

### ISSUE THREAD

**Issue by luckfu** [mudkipme/MoeMemos#11]
![photo_2022-11-21_18-28-37](https://user-images.githubusercontent.com/1396910/203027630-49c45de7-96ce-4797-a201-36cf51ac5eca.jpg)

IOS16.02，iphone13，
Moe Memos 1.1.2(14),
Memos 0.7.3 
刚打开app时tags和附件上传图标是在的，过一会再点击+时，出来编辑界面里就没了。

**Comment by mudkipme** [comment]
Seems I can partly reproduce on iOS 16.1.1. Dismissing and opening the input screen no longer makes the keyboard toolbar disappear. But using photo picker and dismissing can still reproduce this problem. Trying to find a fix.

**Comment by mudkipme** [comment]
This should be fixed with Moe Memos 1.3 😄
