### ISSUE TITLE
Sharing with MoeMemos does not work correctly (iOS)

### ISSUE THREAD

**Issue by mbuczko** [mudkipme/MoeMemos#113]
Testing scenario (iPhone):
- take a photo
- share photo with moe memos
- fill in pop up with some text and send

Expected: new memo added with shared photo
What happens: a progress indicator for a second and then nothing - no error, no memo created

btw. thanks for all your work on this app :)

**Comment by mudkipme** [comment]
Could you provide the version of your Memos server and Moe Memos app version?

If you are using Memos behind a proxy server, please make sure the request body size is set correctly:

```
client_max_body_size 128m;
```

**Comment by mbuczko** [comment]
Thanks for quick answer.

> Could you provide the version of your Memos server and Moe Memos app version?

Memos server: 0.14.4 (based on neosmemo/memos:latest docker image)
MoeMemos: I'm not sure how to check the version - it's latest version from AppStore installed on IOS 16.6 (iPhone 12)

> client_max_body_size 128m;

I'll try to verify that (though server is hosted on Synology which does its own magic with reverse-proxy configuration) but if it was wrong, I presume picture uploads would not work at all? The thing is, they work perfectly well when creating a new memo (with a giant + button) but for some reason don't work when taken picture is being shared with MoeMemos app.

**Comment by mbuczko** [comment]
Checked with `client_max_body_size 128m;` added. Unfortunately, no effect.

**Comment by mudkipme** [comment]
Thanks for the information.

I can reproduce this issue with some of my photos on real device now, guess it's related to memory limit of share extension and/or recent changes of iOS. Will try to fix ASAP.

**Comment by Hconk** [comment]
> Thanks for the information.
> 
> I can reproduce this issue with some of my photos on real device now, guess it's related to memory limit of share extension and/or recent changes of iOS. Will try to fix ASAP.

Thanks for your work.  But now I use iPad OS 16.6.1 and iOS 16.6.1 also  have this problem. I take a screenshot, share to MoeMemos(latest version in App Store, 1.5.5), receive success information, but only send text message.
