### ISSUE TITLE
Ability to take photo [Feature]

### ISSUE THREAD

**Issue by kernelkaribou** [mudkipme/MoeMemos#12]
Hello,

Thanks for making this app and appreciate the respect for privacy. One feature that would be great is to be able to take a photo with the camera to add to a memo.  I see that you can pull from the album but I would love to use this to take photos that I don't really want to save on my phone just quickly capture something.

Thanks again.

**Comment by mudkipme** [comment]
It's planned in next version 😄

**Comment by kernelkaribou** [comment]
Fantastic, thanks!

**Comment by mudkipme** [comment]
1.1.2 is released on App Store.
