### ISSUE TITLE
Cannot login - partial only error displayed

### ISSUE THREAD

**Issue by maticboncina** [mudkipme/MoeMemos#122]
Hi,

I am running the **memos app latest 0.15.1** and I am trying to log in with the Moememos **ios** app, however, I get an error. Unfortunately, **only part of the error** is displayed like this:

![IMG_9241](https://github.com/mudkipme/MoeMemos/assets/54638868/4e10e695-a5a9-4830-b2e4-691f9cc5e776)

Is there anything that can be done to see the full error and troubleshoot this further?

Best, Matic

**Comment by maticboncina** [comment]
As a note of reference, I am inputting the full password, just blurred it out.

**Comment by mudkipme** [comment]
Please upgrade to Moe Memos 1.5.6 to support Memos 0.15 or later.
