### ISSUE TITLE
unable to complete checkboxes on /m/{id}

### ISSUE THREAD

**Issue by markasteadman** [mudkipme/MoeMemos#125]
When linking to a memo using the 'mark' function, the linked post opens in a /m/{Id} page

Checkmarks in this page are not interactive and don't complete

**Comment by mudkipme** [comment]
Currently Moe Memos doesn't support the "Mark" feature yet, which will be supported in future.

For the specific issue related to checkboxes and individual memo page of Memos, please submit an issue to https://github.com/usememos/memos :)
