### ISSUE TITLE
App is incompatible with memos 0.15.2 embedded images

### ISSUE THREAD

**Issue by raisinbear** [mudkipme/MoeMemos#129]
Hi,

first off thanks for the great work! I really enjoy the app 😊
I tried updating my server from memos `0.14.4` to `0.15.2` today. However, the app won't display any of the images I uploaded. They all show just a spinner, same as back in #68 .
On my server I get a ton off messages à la:
`[IP] - - [08/Oct/2023:09:24:11 +0200] "GET /o/r/116/7B2FEFDE-5CAC-47ED-A58D-2401D32EFC5E.jpg?extension=jpg HTTP/2.0" 401 111 "-" "MoeMemos/38 CFNetwork/1474 Darwin/23.0.0"`
This endpoint doesn't exist. At least memos `0.15.2` isn't listening on it.
I'm on the latest version of the iOS app from the official App Store, which nominally should support memos `0.15.x`.

Edit: It appears this only happens when using access tokens. With Username / Password I see no such issue. But I actually thought this sign-in method was disencouraged for some reason..

**Comment by mudkipme** [comment]
Thanks for reporting!

There is indeed an issue with "login with Access Token" and database/local storage on iOS. This will be fixed ASAP.

**Comment by raisinbear** [comment]
Oh wow that was quick. Many thanks! 🎉
