### ISSUE TITLE
Images added by desktop browser don't load in MoeMemos app

### ISSUE THREAD

**Issue by dawidry** [mudkipme/MoeMemos#135]
Problem:
Images which I'm adding on desktop don't load in mobile app (see attached screenshot) - constant loading animation.

Additional tests:
1. I've checked on the same phone if I login to memo via browser all images are loading properly.
2. Additionally images which I'm adding on mobile app (from phone gallery) appears on mobile as well as on desktop. Everything ok here.

![image](https://github.com/mudkipme/MoeMemos/assets/13475936/cdfe2036-c8d7-4da6-9595-dcc1c7f5bc61)

**Comment by mudkipme** [comment]
This is fixed in #130 and would be released soon.
