### ISSUE TITLE
could it support IOS14?

### ISSUE THREAD

**Issue by iyzgit** [mudkipme/MoeMemos#15]
The app only support IOS15&up, could you let it support IOS14?

**Comment by mudkipme** [comment]
Sorry. This app is dependent on a few SwiftUI APIs only supported on iOS 15 or later. As iOS doesn't have Android-like support library which backports APIs to older system, we are unable to add support for iOS 14.

We will keep support for at least two major iOS versions, which means when iOS 17 is out and this app will at least support iOS 16.
