### ISSUE TITLE
ios 使用域名加端口号的方式不能读取server, 但是使用ip加端口号就可以 

### ISSUE THREAD

**Issue by nanshens** [mudkipme/MoeMemos#153]
请问这个可以修复吗

**Comment by mudkipme** [comment]
Moe Memos for iOS doesn't support plain HTTP connection due to Apple's App Transport Security policy (other than connecting to local network via IP address). It’s recommended to use [acme.sh](https://github.com/acmesh-official/acme.sh) to enable HTTPS on your server.

**Comment by ifeitao** [comment]
url like this can't login:  https://memos.example.com:10443

**Comment by hertz-hwang** [comment]
have the same problem. my server hosted on my home, and the port not 443, such as https://mem.xxx.xxx:53443, then the apps can not connects to the server

**Comment by hertz-hwang** [comment]
> > have the same problem. my server hosted on my home, and the port not 443, such as https://mem.xxx.xxx:53443, then the apps can not connects to the server
> 
> You need to install the certificate to the device and trust it if you are using a self-signed certificate for HTTPS: https://support.apple.com/en-us/102390
> 
> BTW, Moe Memos now also supports plain HTTP connection.

YES, I have tried. But, I don't have the option "Enable full trust for root certificates"
