### ISSUE TITLE
Why is the inserted picture compressed?

### ISSUE THREAD

**Issue by klsdfjo** [mudkipme/MoeMemos#157]
I don't want to be compressed because a lot of my pictures are long pictures (3000×15000px）, please can you set the "default upload original image" "

**Comment by klsdfjo** [comment]
The situation I'm talking about appears in the iOS client. I hope that when I record on iOS, the default is to upload the original image, not the compressed image.

**Comment by mudkipme** [comment]
Next version of Moe Memos will no longer resize images when uploading. However it will still be converted to JPEG for compatibility.

I'm considering to add a setting to allow images be uploaded in its original format (such as HEIC) in future.
