### ISSUE TITLE
服务器升级到0.8后，IOS版不能连接了，提示data couldn't be read because it is missing.

### ISSUE THREAD

**Issue by NewOneTcm** [mudkipme/MoeMemos#16]
服务器升级到0.8后，IOS版不能连接了，提示data couldn't be read because it is missing.

我删除了所有的库，重新来一次，也不行，请指导

**Comment by mudkipme** [comment]
This is fixed in upcoming 1.1.2 version, currently pending Apple approval.

In the meantime, please try this build on TestFlight: https://testflight.apple.com/join/YVHheZ50

**Comment by NewOneTcm** [comment]
> This is fixed in upcoming 1.1.2 version, currently pending Apple approval.
> 
> In the meantime, please try this build on TestFlight: https://testflight.apple.com/join/YVHheZ50

非常感谢试了一下可以了。
那个新建时，字体挡住的bug还在
![78BFA9D6-E441-4531-BBD3-5A7F0B0EA4DA](https://user-images.githubusercontent.com/49179435/204091908-357b051a-c271-4790-932e-7ee929c7058b.jpg)

**Comment by NewOneTcm** [comment]
ios 15.1 iphone 13

**Comment by mudkipme** [comment]
1.1.2 with compatibility fix for Memos 0.8.0 is released on App Store.

The UI issue of composing screen will be tracked in https://github.com/mudkipme/MoeMemos/issues/19
