### ISSUE TITLE
IOS can not display picture with newest Memos server 0.19

### ISSUE THREAD

**Issue by netdog2019** [mudkipme/MoeMemos#161]
IOS can not display picture with newest Memos server 0.19

**Comment by alfawei** [comment]
same problem!

**Comment by mudkipme** [comment]
Please try updating to Moe Memos 1.5.8. If the problem persist, please reply with your storage settings, such as storage path and url prefix, as well as whether your filenames contain non-Latin characters.

**Comment by alfawei** [comment]
> Please try updating to Moe Memos 1.5.8. If the problem persist, please reply with your storage settings, such as storage path and url prefix, as well as whether your filenames contain non-Latin characters.

11po iOS 17.3, 1.5.8 same problem
SE3 iOS 16.7.2 1.5.8 same problem
