### ISSUE TITLE
Support strikethrough

### ISSUE THREAD

**Issue by Elbullazul** [mudkipme/MoeMemos#169]
Strikethrough text is already supported on the web app:
![image](https://github.com/mudkipme/MoeMemos/assets/15310985/b28251fb-a55d-44b4-bd50-69f97642f230)

In the Android client it doesn't render properly, only showing the `~~` characters:
![image](https://github.com/mudkipme/MoeMemos/assets/15310985/79da340d-02d0-4702-b445-183385f05f62)

**Comment by AnLuoRidge** [comment]
You should post the issue in Android [repo](https://github.com/mudkipme/MoeMemosAndroid).

**Comment by Elbullazul** [comment]
recreated issue in the [android repo](https://github.com/mudkipme/MoeMemosAndroid/issues/170)
