### ISSUE TITLE
未能读取数据，因为它的格式不正确

### ISSUE THREAD

**Issue by godpowerscn** [mudkipme/MoeMemos#173]
[我使用的memos版本是DOCKER运行的0.20.1，但是使用IOS客户端（1.5.9）登录的时候提示"未能读取数据，因为它的格式不正确"。之前是正常的。请问我该如何解决这个问题？

I am using Memos version 0.20.1 running on DOCKER, but when I log in using the IOS client (1.5.9), it prompts that the data cannot be read because the format is incorrect. It was working fine before. How can I solve this problem?

**Comment by netdog2019** [comment]
same problem~~

**Comment by Eternal37** [comment]
same problem~~
