### ISSUE TITLE
When the version of memos is upgraded to 0.21, the image will not be displayed

### ISSUE THREAD

**Issue by hsiica** [mudkipme/MoeMemos#174]
I can't see my image when words is normal 。

**Comment by mudkipme** [comment]
Memos 0.21 is not released yet. Could you confirm whether you have the same issue with 0.20.1?

**Comment by maycyc** [comment]
I have the same problem, which has lasted for a few days.

**Comment by lorrin328** [comment]
我也是。。。app端图片不显示了，但是网页端还可以

**Comment by alfawei** [comment]
same problem, post new memo, cannot upload photos.

**Comment by netdog2019** [comment]
same problem~~
