### ISSUE TITLE
宿主机环境迁移后无法登录

### ISSUE THREAD

**Issue by Haruhi-Suzumiya** [mudkipme/MoeMemos#179]
我之前使用arm环境（linux）的orangepi作为宿主机，网页登陆和使用moe memos登录都是正常的。
昨晚在x86环境（linux）重新部署docker并使用了原有的数据
现在网页登录正常，moe memos登录提示“未能读取数据，因为它的格式不正确”
这种情况应该怎么排查和解决呢？

**Comment by Haruhi-Suzumiya** [comment]
我的问题似乎得到了解决,把解决方法写在这里供后来者参考:

环境迁移之前,我使用的docker镜像是 lincolnthalles/memos ,它打包的memos版本是v0.21.0
环境迁移之后,我是用的docker镜像是 neosmemo/memos,它打包的memos版本是最新的v0.22.0

所以我怀疑是我更换镜像导致了版本之间的数据不兼容.
在我今天重新使用lincolnthalles/memos 之后,iOS App可以正常登录了

因为在web端是正常的,所以我仍旧倾向于认为这是一个bug
希望作者有时间的话可以看看吧.

以上.

**Comment by mudkipme** [comment]
Moe Memos doesn't support pre-release versions of Memos, as their APIs are unstable and may subject to change. If you are using Docker with Memos, please use `stable` tag or pin the version to `0.21.0`.

You can check the latest version of Memos at https://github.com/usememos/memos/releases.

New release of Memos will be supported by Moe Memos ASAP *after* it is released.

**Comment by Haruhi-Suzumiya** [comment]
> Moe Memos doesn't support pre-release versions of Memos, as their APIs are unstable and may subject to change. If you are using Docker with Memos, please use tag or pin the version to .`stable``0.21.0`
> 
> You can check the latest version of Memos at https://github.com/usememos/memos/releases.
> 
> New release of Memos will be supported by Moe Memos ASAP _after_ it is released.

很奇怪为什么官方的docker配置了预览版,不过感谢您的答复,我明白了.
本件issue就关闭吧
