### ISSUE TITLE
Can't log into MoeMemos receiving error of "The data couldn't be read because it is..."

### ISSUE THREAD

**Issue by raybchoi** [mudkipme/MoeMemos#180]
Recently I was not able to use MoeMemos anymore.

I tried creating a new access code etc but I'm getting the following error: "The data couldn't be read because it is..."

I can't read the entire error b/c it is cut off but screen shot attached.

I'm able to access Memos on my selfhosted site on the web.

Thank you!

I removed the access code in the picture.

<img width="549" alt="image" src="https://github.com/mudkipme/MoeMemos/assets/10458394/d6653724-e9ee-4302-8a0d-259d160932c5">

**Comment by mudkipme** [comment]
Moe Memos doesn't support Memos 0.22.0 yet. Due to major API-breaking changes, it may take longer to release a compatible version.

**Comment by raybchoi** [comment]
Ah I see. Got it - thank you.

Is there any other iOS client that one can use?

**Comment by ZackYJz** [comment]
> Moe Memos doesn't support Memos 0.22.0 yet. Due to major API-breaking changes, it may take longer to release a compatible version.

Could you please recommend a suitable memos version？

**Comment by Lemon7ProPlus** [comment]
> > Moe Memos doesn't support Memos 0.22.0 yet. Due to major API-breaking changes, it may take longer to release a compatible version.
> 
> Could you please recommend a suitable memos version？

0.21.0

Moe Memos currently only supports Memos 0.21.0, as Memos 0.22.0 introduced major API-breaking changes and requires a lot of work to support. Please use the 0.21.0 Docker tag if you are using Moe Memos for now.

**Comment by charliedavison** [comment]
A warning to others that I found that once i had upgraded to 0.22.0 I couldn't go back, it seems there are some migrations that ran that make the database incompatible with the older version.

So im stuck with not being able to use the iOS app unless I want to lose all my previous memos for now.

**Comment by ocean-haiyang** [comment]
this doesn't fix the problem

**Comment by pawel-movelab** [comment]
Any upcoming updates to the iOS app to fix this issue? @mudkipme  🥺
