### ISSUE TITLE
ios16用不了最新的moe memos了吗QAQ

### ISSUE THREAD

**Issue by KAWAKO-in-GAYHUB** [mudkipme/MoeMemos#185]

**Comment by mudkipme** [comment]
Moe Memos 1.6 utilized modern Swift features such as @Observable and SwiftData, which are also foundation of future features like offline use and syncing. Unfortunately and unlike Android counterpart, these features of Apple platforms are unable to backport to earlier versions of iOS or macOS.

**Comment by KAWAKO-in-GAYHUB** [comment]
Understood, I have updated to iOS 17.5.1 and experienced the latest version of MoeMemos. It is very user-friendly. Thank you for your development.
