### ISSUE TITLE
Tags are gone after iOS upgrade to 1.6

### ISSUE THREAD

**Issue by ribtoks** [mudkipme/MoeMemos#188]
Thank you for developing MoeMemos.

I have upgraded on iOS to a new version and all past tags are gone as filters. They are still available in notes.

**Comment by mudkipme** [comment]
That's more likely a update with Memos 0.22: https://github.com/usememos/memos/issues/3502

**Comment by ribtoks** [comment]
Correct, after clicking "Refresh" button, everything is back. Thank you for your help!
