### ISSUE TITLE
Notes editing does not work on iOS 1.6 / memos v0.22.2

### ISSUE THREAD

**Issue by ribtoks** [mudkipme/MoeMemos#189]
Hi

Thank you for developing Moe Memos!

I just noticed that I cannot edit my memos anymore. A gray error popup appears with text "Client error: Unknown..." (the rest is hidden). I tried to open memos website in the browser and editing works there so I assume there's something with the app.

Thank you for any help.

**Comment by mudkipme** [comment]
See https://github.com/mudkipme/MoeMemosAndroid/issues/187#issuecomment-2180452176

**Comment by mudkipme** [comment]
The fix is merged, please try upgrading the server to `neosmemo/memos:latest` or `0.22.3` docker tag.

**Comment by ribtoks** [comment]
I updated and tried the editing in the app again. And it works! Thank you for your help!
