### ISSUE TITLE
New memo dialog “close” button overlaps cursor

### ISSUE THREAD

**Issue by ItsNoted** [mudkipme/MoeMemos#19]
See the screenshot below. I’m using a iPhone 10 Max. 

![C31C2662-A17D-48C1-98B8-A17C65204EAF](https://user-images.githubusercontent.com/57927413/204143279-466d1f15-ce6c-4e85-b711-462821ae3e0e.jpeg)

**Comment by mudkipme** [comment]
This should be fixed with Moe Memos 1.3 😄
