### ISSUE TITLE
低于IOS17的不能下载了吗

### ISSUE THREAD

**Issue by xiamengyo** [mudkipme/MoeMemos#192]
系统是16但商店已经是17系统才能下载了

**Comment by mudkipme** [comment]
Moe Memos 1.6 utilized modern Swift features such as `@Observable` and SwiftData, which are also foundation of future features like offline use and syncing. Unfortunately and unlike Android counterpart, these features of Apple platforms are unable to backport to earlier versions of iOS or macOS.

**Comment by mapxn** [comment]
That's a bad news. I am still using ios15.
