### ISSUE TITLE
需求：iOS小组件

### ISSUE THREAD

**Issue by ShakeChanDev** [mudkipme/MoeMemos#2]
希望能引入类似flomo的桌面小组件

**Comment by mudkipme** [comment]
Yes it's a high priority feature I want to have!

**Comment by mudkipme** [comment]
Added two home screen widgets with https://github.com/mudkipme/MoeMemos/pull/4. The new version is waiting for review on TestFlight.

Please write back if you have any other ideas about home screen widgets and/or lock screen widgets.

**Comment by ShakeChanDev** [comment]
👍🏻应该怎么加入你的testflight

**Comment by mudkipme** [comment]
> 👍🏻应该怎么加入你的testflight

https://testflight.apple.com/join/YVHheZ50

**Comment by mudkipme** [comment]
1.1.1 is released on App Store with Home Screen Widgets.
