### ISSUE TITLE
Update deleted all memos

### ISSUE THREAD

**Issue by blaine07** [mudkipme/MoeMemos#20]
What could I have wrong- every update of docker container is wiping all my memos and deleting them?

**Comment by mudkipme** [comment]
Please add a volume to docker container, with `-v ~/.memos/:/var/opt/memos` for docker run or `volumes` for docker-compose.
See https://github.com/usememos/memos#deploy-with-docker-in-seconds for details.

**Comment by blaine07** [comment]
> Please add a volume to docker container, with `-v ~/.memos/:/var/opt/memos` for docker run or `volumes` for docker-compose.
> See https://github.com/usememos/memos#deploy-with-docker-in-seconds for details.

Is this not right? 

![Uploading 613F592E-D603-4717-8CC4-D1F47730FE72.jpeg…]()

**Comment by blaine07** [comment]
> Please add a volume to docker container, with `-v ~/.memos/:/var/opt/memos` for docker run or `volumes` for docker-compose.
> See https://github.com/usememos/memos#deploy-with-docker-in-seconds for details.

![E23470D6-C5C9-4518-9E93-351D4305E5D3](https://user-images.githubusercontent.com/63940698/204177630-32f870dc-cdbb-476b-b02f-be9625aadceb.jpeg)

**Comment by mudkipme** [comment]
> > Please add a volume to docker container, with `-v ~/.memos/:/var/opt/memos` for docker run or `volumes` for docker-compose.
> > See https://github.com/usememos/memos#deploy-with-docker-in-seconds for details.
> 
> ![E23470D6-C5C9-4518-9E93-351D4305E5D3](https://user-images.githubusercontent.com/63940698/204177630-32f870dc-cdbb-476b-b02f-be9625aadceb.jpeg)

Change
```
-v '/mnt/cache/appdata/memos':'/memos':'rw'
```
to
```
-v '/mnt/cache/appdata/memos':'/var/opt/memos':'rw'
```

**Comment by blaine07** [comment]
> > > Please add a volume to docker container, with `-v ~/.memos/:/var/opt/memos` for docker run or `volumes` for docker-compose.
> > > See https://github.com/usememos/memos#deploy-with-docker-in-seconds for details.
> > 
> > 
> > ![E23470D6-C5C9-4518-9E93-351D4305E5D3](https://user-images.githubusercontent.com/63940698/204177630-32f870dc-cdbb-476b-b02f-be9625aadceb.jpeg)
> 
> Change
> 
> ```
> -v '/mnt/cache/appdata/memos':'/memos':'rw'
> ```
> 
> to
> 
> ```
> -v '/mnt/cache/appdata/memos':'/var/opt/memos':'rw'
> ```

Alright, it came back up. I guess when their is another update I’ll know; or can I force update to see if stuff lasts?
