### ISSUE TITLE
iOS Share Sheet Feature

### ISSUE THREAD

**Issue by zensharp** [mudkipme/MoeMemos#21]
Loving the app so far!

Would it be possible to get a shortcut for iOS Share Sheet? I imagine it looking something like this:

![mockup](https://user-images.githubusercontent.com/48300131/204349321-cc418dd4-79a6-4b5b-b811-066c006ea479.png)

The action would simply wrap calls to the user's OpenAPI endpoint (e.g. `https://memos.example.com/api/memo`).

**Comment by zensharp** [comment]
For a great example, see [Boomerang: Email myself](https://apps.apple.com/us/app/boomerang-email-myself/id1154427984).

**Comment by mudkipme** [comment]
Thanks for the suggestion and example!
Share Extension is definitely on the roadmap 😄

**Comment by mudkipme** [comment]
Moe Memos 1.2 is released with Share Extension 🥰
