### ISSUE TITLE
可以正常登录和看到memos，但是发送和编辑的时候都会报错，如下图

### ISSUE THREAD

**Issue by BenBenJian** [mudkipme/MoeMemos#213]
![image](https://github.com/user-attachments/assets/e89e8e61-fb72-4480-89e3-7a46b33cb270)
可以正常登录和看到memos，但是发送和编辑的时候都会报错
Memos服务器版本 V0.23.0

**Comment by qiyell** [comment]
我的也是，有啥解决办法吗

**Comment by slyang40** [comment]
me too, any solutions? thanks

**Comment by tonyshva** [comment]
same error, server ver 0.23.0

**Comment by Deabal** [comment]
Same error in server ver v0.23.0. It got error in server log:  

> INFO OK method=/memos.api.v1.MemoService/CreateMemo
> ERROR: Failed to extract ServerMetadata from context

**Comment by mudkipme** [comment]
Moe Memos doesn't support pre-release versions of Memos, as their APIs are unstable and may subject to change. If you are using Docker with Memos, please use `stable` tag or pin the version to `0.22.5`.

New release of Memos will be supported by Moe Memos ASAP after it is released.
