### ISSUE TITLE
发布时 the operation could't be completed（OpenAPIRuntime.Runtime）

### ISSUE THREAD

**Issue by KarryZhou** [mudkipme/MoeMemos#216]
![image](https://github.com/user-attachments/assets/0255acc9-41f2-4dca-9e41-4e14839e384f)

**Comment by mudkipme** [comment]
Moe Memos doesn't support pre-release versions of Memos, as their APIs are unstable and may subject to change. If you are using Docker with Memos, please use `stable` tag or pin the version to `0.22.5`.

New release of Memos will be supported by Moe Memos ASAP after it is released.
