### ISSUE TITLE
在手机端点击发送时，服务器响应有点慢，然后会产生多条记录。

### ISSUE THREAD

**Issue by NewOneTcm** [mudkipme/MoeMemos#22]
在手机端点击发送时，服务器响应有点慢，然后会产生多条记录。我在pc端响应很快，不会有多条记录产生，我怀疑是ios的原因，还请确认一下是哪边的问题。

**Comment by mudkipme** [comment]
The app waited for the tag to be reloaded before dismissing the input screen, I guess that might be the cause for delay. It should be asynchronous.

And the app need to disable the submit button when saving the memo.
