### ISSUE TITLE
Please enter a valid input 

### ISSUE THREAD

**Issue by walkcc** [mudkipme/MoeMemos#24]
When I directly copy openApi to text fields, it prompts "Please enter a valid input "

System：IPhone 13 Pro, IOS 16.1.1

Version:  1.1.2

**Comment by mudkipme** [comment]
The Open API should be like:

```
https://{HOST}/api/memo?openId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```

Please make sure there's no white space around the URL in the field.

**Comment by walkcc** [comment]
Oh, Sorry,I accidentally copied an extra space in front of the URL, can we consider automatically removing the spaces before and after the URL ? Thanks a lot.

**Comment by walkcc** [comment]
> 

Huge Thanks！

**Comment by walkcc** [comment]
> Huge Thanks！



> > Oh, Sorry,I accidentally copied an extra space in front of the URL, can we consider automatically removing the spaces before and after the URL ? Thanks a lot.
> 
> Yep! Next version will automatically trim input in login screen.



> > Oh, Sorry,I accidentally copied an extra space in front of the URL, can we consider automatically removing the spaces before and after the URL ? Thanks a lot.
> 
> Yep! Next version will automatically trim input in login screen.

Huge Thanks！

**Comment by walkcc** [comment]
> > Oh, Sorry,I accidentally copied an extra space in front of the URL, can we consider automatically removing the spaces before and after the URL ? Thanks a lot.
> 
> Yep! Next version will automatically trim input in login screen.

Huge Thanks！

**Comment by mudkipme** [comment]
Moe Memos 1.2 is released with improvement to login screen. 😃
