### ISSUE TITLE
can not log in！

### ISSUE THREAD

**Issue by chaunceyPan** [mudkipme/MoeMemos#26]
I log in with my account password or API on the app and it says I can't log in。

Error code: The resource could not be loaded  because the App Transport Security policy requires the use of a secure con...

IOS 16.1.1(20B101)

**Comment by mudkipme** [comment]
The App Transport Security policy of iOS requires HTTPS (or local network) for your security. It’s recommended to use [acme.sh](https://github.com/acmesh-official/acme.sh) to enable HTTPS on your server.

**Comment by writepavel** [comment]
Hi 👋 I faced the same issue and I've found out how to solve it in my case. 

My issue root cause was slash "/" at the end of memos domain in settings. 

"https://subdomain.domain.net/" caused this error but "https://subdomain.domain.net" works well for me.
Kind regards, Pavel
