### ISSUE TITLE
The app is not available in some regions

### ISSUE THREAD

**Issue by vslinko** [mudkipme/MoeMemos#27]
Hi! I want to download the app from the Russian App Store but I get the error "This app is currently not available in your country or region.".

**Comment by mudkipme** [comment]
I'm sorry that to avoid transactions indirectly linking to the regimes responsible for invading neighbor country, the app isn't currently available on App Store and Google Play in Russia and Belarus regions.

This doesn't mean to offend or let down Russian and Belarusian people who don't support the ongoing invasion and it is not a political statement. And you are welcome to use this app! (I'm a user of Obsidian Outliner.)

For alternative you can:
1. Clone and build this app with Xcode and run on your own devices.
2. Download from TestFlight: https://testflight.apple.com/join/YVHheZ50
3. Register an Apple ID of another region and use that for App Store. (*Recommended.* Personally I have Apple IDs of 4 regions to workaround regional restrictions.)

If you use Android devices it's welcome to download from F-Droid.

**Comment by vslinko** [comment]
Thanks for workarounds. Do you have iPad and Mac versions in TestFlight?

**Comment by mudkipme** [comment]
> Thanks for workarounds. Do you have iPad and Mac versions in TestFlight?

Yes! The TestFlight version is available on iPad and Macs with Apple Silicon too. (using the same link)

The app currently doesn't support Intel Macs as the web version of Memos has superior experience on desktop. It may be a native Mac app someday when it's more polished :)

**Comment by vslinko** [comment]
I have only iOS version in TestFlight by this link :(
<img width="366" alt="Screenshot 2022-12-23 at 20 28 33" src="https://user-images.githubusercontent.com/205823/209376546-a51be928-5c32-43f9-8080-5532c290d14a.png">

**Comment by vslinko** [comment]
Ow, I got it, I have Intel :)
