### ISSUE TITLE
Feature: multiple instances

### ISSUE THREAD

**Issue by jxpsert** [mudkipme/MoeMemos#28]
Currently, one can only be logged into one instance of Memos. Would it be possible to provide the option to be logged into multiple and switch between them, like in the [Wordpress app](https://apps.files.wordpress.com/2020/12/annotation-on-2020-12-21-at-13-30-40.png)?

I personally host 2 instances of Memos, and would love this feature.

**Comment by mudkipme** [comment]
Thanks for this feature request!

I'll put multi accounts support on the roadmap and hope to implement it early next year 😁
