### ISSUE TITLE
ios强退后需要重新登陆

### ISSUE THREAD

**Issue by luckfu** [mudkipme/MoeMemos#3]
ios上，上滑app强制退出后，需要重新登陆

**Comment by mudkipme** [comment]
Looks like the same issue with: https://github.com/mudkipme/MoeMemosAndroid/issues/1#issuecomment-1298752150

**Comment by luckfu** [comment]
> Looks like the same issue with: [mudkipme/MoeMemosAndroid#1 (comment)](https://github.com/mudkipme/MoeMemosAndroid/issues/1#issuecomment-1298752150)

我并没有重启服务器，这两天使用下来，发现这还是常态化的，也就是说在ios下，并没有上滑强制关闭app，隔几个小时后再打开，也可能需要重登录，ios16.02

**Comment by mudkipme** [comment]
Thanks for the feedback. As I can't reproduce this issue, I guess it has something to do with how URLSession stores and uses cookies.

To avoid this problem once and for all, I'm planning to add an alternative login method: *login with Open API*. It will store the `openId` and no longer uses cookie.

**Comment by mudkipme** [comment]
Please try the new TestFlight build: https://testflight.apple.com/join/YVHheZ50

This version added a new login method: Sign in with Open API. It will keep your login status as long as the Open API isn't reset.

![Simulator Screen Shot - iPhone 13 mini - 2022-11-16 at 00 44 57](https://user-images.githubusercontent.com/518069/201977816-c7888108-ee8c-4202-9d7f-59f7fdf695d4.png)

**Comment by mudkipme** [comment]
Sign in with Open API is released on App Store.
