### ISSUE TITLE
iOS client v1.2, server v0.9.1 : can't connect

### ISSUE THREAD

**Issue by yinzhekong** [mudkipme/MoeMemos#30]
"data couldn't be read because it is missing."

**Comment by mudkipme** [comment]
Currently Moe Memos is not compatible with Memos v0.9.1's [CSRF](https://github.com/usememos/memos/commit/c9bb2b785dc5852655405d5c9ab127a2d5aa3948#diff-78f42ba40d0f10b08c73b7e6bb8376f398e249c963cf549e89591d6b6826b9a4) method. It will be fixed in next version.

For now, please try signing in with Open API.

**Comment by yinzhekong** [comment]
> Currently Moe Memos is not compatible with Memos v0.9.1's [CSRF](https://github.com/usememos/memos/commit/c9bb2b785dc5852655405d5c9ab127a2d5aa3948#diff-78f42ba40d0f10b08c73b7e6bb8376f398e249c963cf549e89591d6b6826b9a4) method. It will be fixed in next version.
> 
> 
> 
> For now, please try signing in with Open API.

Open API won't work too.

**Comment by mudkipme** [comment]
> > Currently Moe Memos is not compatible with Memos v0.9.1's [CSRF](https://github.com/usememos/memos/commit/c9bb2b785dc5852655405d5c9ab127a2d5aa3948#diff-78f42ba40d0f10b08c73b7e6bb8376f398e249c963cf549e89591d6b6826b9a4) method. It will be fixed in next version.
> > For now, please try signing in with Open API.
> 
> Open API won't work too.

I can't reproduce this issue with Open API login and Memos 0.9.1. Could you please reply with the output of this API with your web browser:

```
https://{YOUR_MEMOS_HOST}/api/user/me
```

Please make sure to remove the JSON value of your personal information such as `email` and `openId`.

**Comment by yinzhekong** [comment]
> > > Currently Moe Memos is not compatible with Memos v0.9.1's [CSRF](https://github.com/usememos/memos/commit/c9bb2b785dc5852655405d5c9ab127a2d5aa3948#diff-78f42ba40d0f10b08c73b7e6bb8376f398e249c963cf549e89591d6b6826b9a4) method. It will be fixed in next version.
> 
> > > For now, please try signing in with Open API.
> 
> > 
> 
> > Open API won't work too.
> 
> 
> 
> I can't reproduce this issue with Open API login and Memos 0.9.1. Could you please reply with the output of this API with your web browser:
> 
> 
> 
> ```
> 
> https://{YOUR_MEMOS_HOST}/api/user/me
> 
> ```
> 
> 
> 
> Please make sure to remove the JSON value of your personal information such as `email` and `openId`.

Output of `http://{MY_MEMOS_HOST}/api/user/me` :
```

{"data":{"id":1,"rowStatus":"NORMAL","createdTs":1672481260,"updatedTs":1672481611,"username":"","role":"HOST","email":"","nickname":"","openId":"","userSettingList":[{"UserID":1,"key":"memoVisibility","value":"\"PROTECTED\""}]}}

```
(Private value removed)

By the way, my server don't support https.

I get the content of all two memoses from open api with browser.

**Comment by yinzhekong** [comment]
> > Currently Moe Memos is not compatible with Memos v0.9.1's [CSRF](https://github.com/usememos/memos/commit/c9bb2b785dc5852655405d5c9ab127a2d5aa3948#diff-78f42ba40d0f10b08c73b7e6bb8376f398e249c963cf549e89591d6b6826b9a4) method. It will be fixed in next version.
> > 
> > 
> > 
> > For now, please try signing in with Open API.
> 
> Open API won't work too.

"The resource could not be loaded be..."

**Comment by mudkipme** [comment]
> > > Currently Moe Memos is not compatible with Memos v0.9.1's [CSRF](https://github.com/usememos/memos/commit/c9bb2b785dc5852655405d5c9ab127a2d5aa3948#diff-78f42ba40d0f10b08c73b7e6bb8376f398e249c963cf549e89591d6b6826b9a4) method. It will be fixed in next version.
> > > For now, please try signing in with Open API.
> > 
> > 
> > Open API won't work too.
> 
> "The resource could not be loaded be..."

The App Transport Security policy of iOS requires HTTPS (or local network). It's recommended to use [acme.sh](https://github.com/acmesh-official/acme.sh) to enable HTTPS on your server.

If your server is in your local network, please try connecting with IP address (such as `http://192.168.1.10:5230`).

**Comment by yinzhekong** [comment]
> > > > Currently Moe Memos is not compatible with Memos v0.9.1's [CSRF](https://github.com/usememos/memos/commit/c9bb2b785dc5852655405d5c9ab127a2d5aa3948#diff-78f42ba40d0f10b08c73b7e6bb8376f398e249c963cf549e89591d6b6826b9a4) method. It will be fixed in next version.
> 
> > > > For now, please try signing in with Open API.
> 
> > > 
> 
> > > 
> 
> > > Open API won't work too.
> 
> > 
> 
> > "The resource could not be loaded be..."
> 
> 
> 
> The App Transport Security policy of iOS requires HTTPS (or local network). It's recommended to use [acme.sh](https://github.com/acmesh-official/acme.sh) to enable HTTPS on your server.
> 
> 
> 
> If your server is in your local network, please try connecting with IP address (such as `http://192.168.1.10:5230`).

Thanks!
