### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by zerak** [mudkipme/MoeMemos#45]
iOS version: `16.3`
App version：`appStore Version 1.3.3`
memos server version：docker image: `neosmemo/memos:0.10.3`

server error log：
> {
"time": "2023-02-22T07:20:40Z",
"method": "GET",
"uri": "/api/memo/auth?openId=my-openID",
"status": 400,
"error": "code=400, message=ID is not a number: auth, internal=strconv.Atoi: parsing \"auth\": invalid syntax"
}

@mudkipme

**Comment by zerak** [comment]
iOS version: 16.3

**Comment by mudkipme** [comment]
It seems you have selected login with "Username and Password" but also input a Open API address in the "Host" field. Please try switching to "Open API" login or removing the `/api/memo?openId=your-openID` part from the "Host" field.

**Comment by zerak** [comment]
> 
It was my mistake, I can indeed log in now
