### ISSUE TITLE
拍照上传错误

### ISSUE THREAD

**Issue by Juskinbo** [mudkipme/MoeMemos#49]
当使用moememos软件内部拍照上传时报错。
![image](https://user-images.githubusercontent.com/54654557/222623869-f18f145c-270e-4df8-975a-8e861c496e1c.png)

**Comment by xu4wang** [comment]
@Juskinbo 请问解决了吗？ 我今天也碰到了。

**Comment by Juskinbo** [comment]
@xu4wang 我memos是使用docker部署的，然后用nginx代理，这个报错好像是来自于nginx，nginx 配置文件中的client_max_body_size用于控制请求body的大小限制的参数，默认为1MB，如果超过这个数值，则会直接返回413状态码，所以如果图片过大就会报错，可以修改nginx的配置文件然后reload一下。
