### ISSUE TITLE
发布时带新标签（没有用过）时，没有在memos中创建新标签。

### ISSUE THREAD

**Issue by skyue** [mudkipme/MoeMemos#58]
https://github.com/usememos/memos/issues/1310#issuecomment-1465986967

之前在memos项目中提的，发现是客户端的问题，可参考上面这个链接。

**Comment by qrzbing** [comment]
Hi, I think we can discuss some details in this issue: https://github.com/mudkipme/MoeMemosAndroid/issues/54

**Comment by skyue** [comment]
> Hi, I think we can discuss some details in this issue: [mudkipme/MoeMemosAndroid#54](https://github.com/mudkipme/MoeMemosAndroid/issues/54)

haha, good.
