### ISSUE TITLE
Android moememos app DOCKER 配合DDNS经常需要重新登录

### ISSUE THREAD

**Issue by czxinshui** [mudkipme/MoeMemos#6]
Android moememos app DOCKER 配合DDNS经常需要重新登录
麻烦添加记住服务器、账号、密码 的功能，免得每次DDNS发生变化就需要重新登录
Android APP 1.0.0

**Comment by mudkipme** [comment]
Please check https://github.com/mudkipme/MoeMemosAndroid/issues for issues about the Android version.

For this specific issue, Moe Memos 0.2.0 for Android is released with "Sign in with Open API" option. It will keep your login status even if the session is expired or the server restarted.

Moe Memos 1.1 for iOS will add the same feature and it has been submitted to App Store, should be available soon.
