### ISSUE TITLE
希望增加一些可选图标

### ISSUE THREAD

**Issue by erbanku** [mudkipme/MoeMemos#64]
原始图标不错，可是难免有些复古，希望增加一些可选图标。

> 注：来自一个强迫症客户端🤣

**Comment by izuolan** [comment]
这个图标的格子图占太满图标了, 要是距离图标边缘多一些就好看了. 或者用 memos 新图标也不错~

**Comment by erbanku** [comment]
确实，建议采用Memos新图标
