### ISSUE TITLE
image can't be loaded.

### ISSUE THREAD

**Issue by ajason** [mudkipme/MoeMemos#68]
The image is not previewing and I can't view it on the web even after sending it.
![image](https://user-images.githubusercontent.com/786267/232821443-eda5e372-1f40-48c2-b3ad-fe6d1da9bbc4.png)

**Comment by mudkipme** [comment]
Please provide your storage setting. Is it database, local, or s3-based storage? If it's a S3 based storage, please also provide your storage provider. (S3, Backblaze B2, Cloudflare R2, Minio, etc)

**Comment by Albatrosicks** [comment]
> Please provide your storage setting. Is it database, local, or s3-based storage? If it's a S3 based storage, please also provide your storage provider. (S3, Backblaze B2, Cloudflare R2, Minio, etc)

Same on database storage and local storage. 
memos version is v0.12.2
MoeMemos version is v1.5
Also, the iOS share button does not work for uploading a media file. Only text is saved. I don't know if it's the same reason or not.

**Comment by purkylin** [comment]
Maybe the image format is not supported, You should give the url of problem image, so that developer can positioning the problem

**Comment by ajason** [comment]
The issue was related to storage permissions and has been resolved.
