### ISSUE TITLE
Can not login with Open API

### ISSUE THREAD

**Issue by wrayck** [mudkipme/MoeMemos#70]
Very good app, thanks. I deployed a memos server (ver.0.12.1) in my Synology NAS. I tried use my Memos Open API to create a shortcut in iOS
and it’s working just fine.  Unfortunately, I can’t login with Open API in Meo memos app, neither with domain name nor public IP. It seems only Local IP can be accessed successfully. I would be appreciated if someone could tell me the reason, Thanks!

**Comment by mudkipme** [comment]
The App Transport Security policy of iOS requires HTTPS for your security. It’s recommended to use [acme.sh](https://github.com/acmesh-official/acme.sh) to enable HTTPS on your server.

I'm also planning to try submitting a version with NSAllowsArbitraryLoads, but I'm not sure that will be approved by Apple.
