### ISSUE TITLE
希望可以记住上次的可见性

### ISSUE THREAD

**Issue by fengqi** [mudkipme/MoeMemos#72]
网页上可以使用设置的默认可见性，发布内容的时候就不会再去操作选一下。
App上发过几条才发现只有自己可见，无奈挨个手动修改下，然后发现每次发布都要再选下可见性。
不确定能不能读取用户设定，如果能记住上次的可能更好。

**Comment by mudkipme** [comment]
It should be default to the user's memo visibility setting. Seems like a compatibility issue with newer version of Memos.
