### ISSUE TITLE
编辑memo后的发布按钮没有做防抖处理，会清空memo

### ISSUE THREAD

**Issue by kingname** [mudkipme/MoeMemos#77]
1. 先发布1条memo
2. 编辑这条memo，随便加点内容进来
3. 快速点击2次右上角的发布按钮
4. 这条memo变成空白

===

1. publish a memo first
2. edit this memo, write anything on it
3. click the publish button twice in second
4. the memo will become empty.

**Comment by mudkipme** [comment]
Fixed with #84

**Comment by kingname** [comment]
@mudkipme when will this patch be deployed to apple store?

**Comment by mudkipme** [comment]
> @mudkipme when will this patch be deployed to apple store?

Hopefully next weekend with v1.6.
