### ISSUE TITLE
Search bar glitch

### ISSUE THREAD

**Issue by themagiulio** [mudkipme/MoeMemos#78]
When I move from the menu to the memos page, the search bar glitches because it disappears.

https://github.com/mudkipme/MoeMemos/assets/18516031/d5379bf4-a5be-4a40-86bc-d7e59e0fe01c

**Comment by mudkipme** [comment]
Haven't tested yet but it's hopefully fixed with iOS 17.

Or at least iOS 17 has the new `searchable` API to manually fix this issue.
