### ISSUE TITLE
error when uploading a photo taken by camera

### ISSUE THREAD

**Issue by xu4wang** [mudkipme/MoeMemos#79]
## Reproduce procedure

1. add a new post
2. click the camera (3rd icon) on the toolbar. 
3. take a photo and use it
4. an error message shows up, see below
![image](https://github.com/mudkipme/MoeMemos/assets/311397/4ebf5ddf-5c80-4676-a902-1d28518dcda5)

Is it a configuration issue of my server?

**Comment by mudkipme** [comment]
If you put your Memos server behind a proxy, please increase the maximum allowed size of the client request body. Here’s the nginx configruation for example:

> client_max_body_size 128m;

**Comment by xu4wang** [comment]
thanks
