### ISSUE TITLE
0.15.3兼容memos 0.14.0问题

### ISSUE THREAD

**Issue by skyue** [mudkipme/MoeMemos#98]
登录时提示未能读取到数据，因为格式不正确。

APP：ios 0.15.3
Memos：0.14.0正式版之后的最新test版

按理0.14.0之后的test版应该没再改动api，不知道为什么0.15.3还是提示这个错误。

**Comment by gujin03** [comment]
遇到同样的问题

**Comment by Lclcng** [comment]
0.14.1也是无法登陆，提示未能读取到数据，因为格式不正确。

**Comment by cfboss** [comment]
肯定大佬新版本兼容也 遇到了同样的问题

**Comment by mudkipme** [comment]
Fixed with #99 and submitted to App Store.
